[package]
name = "tdd_hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
http-body-util = "0.1.1"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
